$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: used-cars-train-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: ../../../data-science/environment/train-conda.yml
description: "Custom Python 3.10 environment for used car price prediction training, featuring scikit-learn 1.2.0 and MLflow tracking."