$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command 
name: train_model
display_name: train-model-component
inputs: 
  train_data:
    type: uri_folder  # Must be uri_folder to match prep.py output
  test_data:
    type: uri_folder  # Must be uri_folder to match prep.py output
  n_estimators:
    type: integer  
    default: 100 
  max_depth:
    type: integer     # n_estimators and max_depth are both integers
    default: 10      # Standard default for Random Forest depth
outputs:
  model_output:
    type: mlflow_model  # Crucial: This allows the Register step to read it
code: ../../../data-science/src
command: >-
  python train.py 
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}
environment: azureml:used-cars-train-env@latest